# Generated by Django 5.0.4 on 2024-05-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image_post_likes_alter_post_body_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='post',
        ),
    ]
